spring:
  config:
    import: optional:file:.env[.properties]
  jackson:
    time-zone: Asia/Seoul

  datasource:
    url: jdbc:oracle:thin:@//${DB_HOST}:${DB_PORT}/semiconductor
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database: oracle
    generate-ddl: false
