spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database: oracle
    generate-ddl: false

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false