export interface CorporateCardTransactionData {
  id: string;
  status: string;
  approvalNumber: string;
  approvalDate: string;
  cardType: string;
  isCancelled: boolean;
  merchantName: string;
  merchantCategory: string;
  merchantOwnerName: string;
  merchantAddress: string;
  businessRegistrationNumber: string;
  transactionAmount: number;
  splitCount: number;
  supplyAmount: number | null;
  taxAmount: number;
  accountName: string | null;
  projectCode: string | null;
  projectName: string | null;
  description: string | null;
  transactionDate: string;
  fileName: string | null;
  filePath: string | null;
  attachRejectionReason: string | null;
  preApprovalFileName: string | null;
  preApprovalFilePath: string | null;
  userId: string;
  cardCompany: string;
  cardNumber: string;
  gridRowId: string | null;
}